# HTTP → HTTPS редирект
server {
    listen 80;
    server_name pet2.local;

    return 301 https://$host$request_uri;
}

# HTTPS сервер
server {
    listen 443 ssl;
    server_name pet2.local;

    charset utf-8;

    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    root /home/vito/nginx-lab/sites/site2;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
