# HTTP → HTTPS редирект
server {
    listen 80;
    server_name pet1.local;

    return 301 https://$host$request_uri;
}

# Основной HTTPS сервер
server {
    listen 443 ssl;
    server_name pet1.local;

    charset utf-8;

    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    root /home/vito/nginx-lab/sites/site1;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /shared/ {
        alias /home/vito/nginx-lab/sites/shared/;
        autoindex on;
        charset utf-8;   # важно для txt
    }
}
