name: Good CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Lint passed"

  test:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - run: echo "Tests passed"

  security:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - run: echo "Security check passed"

  build:
    runs-on: ubuntu-22.04
    needs: security
    steps:
      - run: echo "Build passed"

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - run: echo "Deploy passed"
